# Generated by Django 5.2.5 on 2025-09-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='specializationmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
